/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.casoobserver.Subasta;

/**
 *
 * @author valer
 */
public class Subasta_GUI extends javax.swing.JFrame {
    private static final String SERVER_IP = "127.0.0.1";
    private static final int SERVER_PORT = 9090;
    public Subasta subasta;
    
    public Subasta_GUI(Subasta subasta) {
        this.subasta = subasta;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lbl_subastador = new javax.swing.JLabel();
        Lbl_producto = new javax.swing.JLabel();
        Lbl_lastOfert = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSpinner1 = new javax.swing.JSpinner();
        btn_aceptar = new javax.swing.JButton();
        cerrar_Btn = new javax.swing.JButton();
        cancelar_btn = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Lbl_subastador.setText("Subastador: ");
        jPanel1.add(Lbl_subastador, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, -1));

        Lbl_producto.setText("Producto:");
        jPanel1.add(Lbl_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, -1));

        Lbl_lastOfert.setText("Utima Oferta:");
        jPanel1.add(Lbl_lastOfert, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 240, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, 120));
        jPanel1.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 80, -1));

        btn_aceptar.setText("ACEPTAR OFERTA");
        jPanel1.add(btn_aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        cerrar_Btn.setText("CERRAR");
        jPanel1.add(cerrar_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 90, -1));

        cancelar_btn.setText("CANCELAR");
        jPanel1.add(cancelar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        jTextField1.setText("Felicidades");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void initSubasta (Subasta subasta) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subasta_GUI(subasta).setVisible(true);
                
                System.out.println("llega");
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lbl_lastOfert;
    private javax.swing.JLabel Lbl_producto;
    private javax.swing.JLabel Lbl_subastador;
    private javax.swing.JButton btn_aceptar;
    private javax.swing.JButton cancelar_btn;
    private javax.swing.JButton cerrar_Btn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
